### ISSUE TITLE
SSL cert installed

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#76] opened 2016-01-12 20:35 UTC
To do this, we need to generate a CSR file from within the host, give it to whomever is issuing the cert and then install the cert they give us.

**Comment by joelworsham** [comment] 2016-01-12 22:18
I think this is a duplicate of #62. I'll just close 62 and leave this one open.

**Comment by d4mation** [comment] 2018-09-19 18:53
Seems to have been done

![image](https://user-images.githubusercontent.com/7770631/45774727-bca6ff80-bc1b-11e8-9ea8-9de6500621a3.png)

**Closed by d4mation** 2018-09-19 18:53 UTC
Labels: enhancement, lower priority
