### ISSUE TITLE
Broken links from events

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#316] opened 2020-12-07 12:51 UTC
Hello, this is more of a nit picky issue, but we have a web governance tool called SiteImprove and it shows any broken links. I've noticed over the last few months that I'm getting broken links for oembed invalid url for our events? This is more of a nuisance in SiteImprove since there are not broken links in the actual event, it's just annoying to get a notification that there are 100 broken links and they are just for these oembed urls.

For instance, this is what the broken link looks like:

https://www.jccmi.edu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.jccmi.edu%2Fevents%2Fcentral-michigan-university-main-campus-virtual-transfer-visit%2F&format=xml

and when I click on that link in SiteImprove the explanation is:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<oembed>
<code>oembed_invalid_url</code>
<message>Not Found</message>
<data>
<status>404</status>
</data>
</oembed>

**Comment by d4mation** [comment] 2020-12-07 14:52
I found the cause for this. It is because your Events plugin assigns a custom Post Status for when an Event has passed which the oEmbed system doesn't like. 

I'll see if I can trick it into thinking the Event is published only when it is calling for an oEmbed to get around this issue while not breaking the oEmbed functionality for all Events.

**Comment by d4mation** [comment] 2020-12-07 15:23
Pushed a fix for the bug. This is all set :+1:

**Closed by d4mation** 2020-12-07 15:23 UTC
Labels: bug

**Comment by banksashleym** [comment] 2020-12-07 15:31
Awesome, thanks so much!
